AnimalShelter/Models/Database.cs
using System;
using MySql.Data.MySqlClient;
using AnimalShelter;

namespace AnimalShelter.Models
{
  public class DB
  {
    public static MySqlConnection Connection()
    {
      MySqlConnection conn = new MySqlConnection(DBConfiguration.ConnectionString);
      return conn;
    }
  }
}

AnimalShelter/Models/Detail.cs
namespace AnimalShelter.Models
{
    public class Detail
    {
        public int DetailId { get; set; }
        public string Description { get; set; }

        public int TypeClassId { get; set; }
        public virtual TypeClass TypeClass { get; set; }
    }
}

AnimalShelter/Models/Type.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
    public class TypeClass
    {
        public TypeClass()
        {
            this.DetailGroup = new HashSet<Detail>();
        }

        public int TypeClassId { get; set; }
        public string Name { get; set; }
        // public int RestaurantId { get; set; }
        public virtual ICollection<Detail> DetailGroup { get; set; }
    }
}

AnimalShelter/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AnimalShelter.Controllers
{
    public class DetailGroupController : Controller
    {
        private readonly AnimalShelterContext _db;

        public DetailGroupController(AnimalShelterContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Detail> model = _db.DetailGroup.Include(detailGroup => detailGroup.TypeClass).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.TypeClassId = new SelectList(_db.TypeClassGroup, "TypeClassId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Detail detail)
        {
            _db.DetailGroup.Add(detail);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Detail thisDetail = _db.DetailGroup.FirstOrDefault(detailGroup => detailGroup.DetailId == id);
            return View(thisDetail);
        }

        public ActionResult Edit(int id)
        {
            var thisDetail = _db.DetailGroup.FirstOrDefault(detailGroup => detailGroup.DetailId == id);
            ViewBag.TypeClassId = new SelectList(_db.TypeClassGroup, "TypeClassId", "Name");
            return View(thisDetail);
        }

        [HttpPost]
        public ActionResult Edit(Detail detail)
        {
            _db.Entry(detail).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisDetail = _db.DetailGroup.FirstOrDefault(detailGroup => detailGroup.DetailId == id);
            return View(thisDetail);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisDetail = _db.DetailGroup.FirstOrDefault(detailGroup => detailGroup.DetailId == id);
            _db.DetailGroup.Remove(thisDetail);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAll()
        {
            var allDetailGroup = _db.DetailGroup.ToList();
            return View();
        }

        [HttpPost, ActionName("DeleteAll")]
            public ActionResult DeleteAllConfirmed()
        {
            var allDetailGroup = _db.DetailGroup.ToList();

        foreach (var detail in allDetailGroup)
        {
            _db.DetailGroup.Remove(detail);
        }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/Controllers/TypeClassController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Controllers
{
  public class TypeClassGroupController : Controller
  {
    private readonly AnimalShelterContext _db;

    public TypeClassGroupController(AnimalShelterContext _db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<TypeClass> model = _db.TypeClassGroup.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(TypeClass typeClass)
    {
      _db.TypeClassGroup.Add(typeClass);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      TypeClass thisTypeClass = _db.TypeClassGroup.FirstOrDefault(typeClass => typeClass.TypeClassId == id);
      return View(thisTypeClass);
    }

    public ActionResult Edit(int id)
    {
      var thisTypeClass = _db.TypeClassGroup.FirstOrDefault(typeClass => typeClass.TypeClassId == id);
      return View(thisTypeClass);
    }

    [HttpPost]
    public ActionResult Edit(TypeClass typeClass)
    {
      _db.Entry(typeClass).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTypeClass = _db.TypeClassGroup.FirstOrDefault(typeClass => typeClass.TypeClassId == id);
      return View(thisTypeClass);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTypeClass = _db.TypeClassGroup.FirstOrDefault(typeClass => typeClass.TypeClassId == id);
      _db.TypeClassGroup.Remove(thisTypeClass);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult DeleteAll()
    {
      var allTypeClassGroup = _db.TypeClassGroup.ToList();
      return View();
    }

    [HttpPost, ActionName("DeleteAll")]
    public ActionResult DeleteAllConfirmed()
    {
      var allTypeClassGroup = _db.TypeClassGroup.ToList();

      foreach (var typeClass in allTypeClassGroup)
      {
      _db.TypeClassGroup.Remove(typeClass);
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

AnimalShelter/Views/Details/DeleteAll.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Delete All</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
    <h1>Your list has been cleared!</h1>
    <p><a href="/details">Back to List</a></p>
</body>
</html>

AnimalShelter/Views/Details/Index.cshtml
@using AnimalShelter.Models;

<h1>Animal Shelter</h1>
<!-- Adding Items -->
@if(Model.Count == 0)
{
  <p>There is no info in the list!</p>
}
<ul>
  @foreach(Detail detail in Model)
  {
    <li>
      <a href="/details/@detail.Id">
        @detail.Name
      </a>
    </li>
  }

</ul>
<a href="/details/new"> Add a new info.</a>

<!-- deleting details -->
<form action="/details/delete" method="post">
  <button type="submit" name="button">Clear All Info</button>
</form>

AnimalShelter/Views/Details/New.cshtml
@{
  Layout = "_Layout";
}

<center>
<h1 style="margin-left: 40px">Add New Animal To Type: <strong><i>@Model.Name</i></strong></h1>
<br>
<form style="margin-left: 40px" action="/typesClass/@Model.Id/details" method="post">
  <input id="vendorId" name="vendorId" type="hidden" value="@Model.Id">
  <label for="detailDescription">Animal Name</label>
  <input id="detailDescription" name="detailName" type="text">

  <label for="genderName">Gender</label>
  <input id="genderName" name="genderName" type="text">

  <label for="breedName">Breed</label>
  <input id="breedName" name="breedName" type="text">

  <label for="admittDateName">Admitted Date</label>
  <input id="admittDateName" name="admittDateName" placeholder="mm/dd/yyyy" type="date">
  <br>
  <br>
  <br>
  <button class="btn btn-success" type='submit'>Add Animal</button>
</form>
</center>

AnimalShelter/Views/Details/Show.cshtml
@{
  Layout = "_Layout";
}
<center>
<h1><b><i>@Model["typeClass"].Description</i></b> Details</h1>
<br>
<h3>Namedor: <b>@Model["typeClass"].Name</b></h3>
<h3>Order of: <b>@Model["detail"].Gender</b></h3>
<h3>Quantity: <b>@Model["detail"].Breed</b></h3>
<h3>Date: <b>@Model["detail"].AdmittDate</b></h3>
<br>
<br>
@* <p><a href='/vendors/@Model["vendor"].Id/order/@Model["order"].Id/orders/new'>Edit Order</a></p> *@

@* <p><a href='/vendors/@Model["vendor"].Id/order/@Model["order"].Id/delete'>Delete Order</a></p> *@

<form action="/details/delete" method="post">
  <button class="btn btn-success" type='submit'>Delete Order</button>
</form>
<br>
<p><a href='/typesClass/@Model["vendor"].Id'>Order Overview</a></p>

</center>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<center>

<h1>Animal Shelter</h1>
<br>
<h4>Add an animal type first!</h4>
<br>
<hr />
<br>
<p>@Html.ActionLink("Search by Animal Type", "Index", "TypeClassGroup")</p>
<br>
<p>@Html.ActionLink("Search by Animal Name", "Index", "DetailGroup")</p>
</center>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Animal Shelter</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

AnimalShelter/Views/TypesClass/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Types</h1>
    @if(@Model.Count == 0)
    {
        <h3>No types have been added yet!</h3>
    }
    @foreach (TypeClass typeClass in Model)
    {
        <h3><a href="/typesClass/@typeClass.Id">@typeClass.Name</a></h3>
    }
    <p><a href="/">Home</a></p>
</body>
</html>

AnimalShelter/Views/TypesClass/New.cshtml
<h1>Add a type</h1>
<p>Add a type here:</p>

<form action="/typesclass" method="post">
  <label for="typeClassName">Type name</label>
  <input id="typeClassName" name="typeClassName" type="text">
  <button type="submit">Add</button>
</form>

<p><a href="/">Home</a></p>
<p><a href="/typesClass">Back to types overview</a></p>

AnimalShelter/Views/TypesClass/Show.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Show Type List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    @using AnimalShelter.Models;
    <h3>Here are all the animals in this type:</h3>
    <ol>
        @foreach (var detail in @Model["details"])
        {
            <li><a href='/typesClass/@Model["typeClass"].TypeClassId/details/@detail.DetailId'>@detail.Name</a></li>
        }
    </ol>
    <p><a href='/typesClass/@Model["typeClass"].TypeClassId/details/new'>Add a new animal</a></p>
    <p><a href='/typesClass'>Return to types overview</a></p>
    <p><a href='/'>Return to Main Page</a></p>
</body>
</html>